package com.jinyb.crawler.entity;

// Generated 2013-3-15 11:43:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * News generated by hbm2java
 */
public class News implements java.io.Serializable {

	private int newsId;
	private String newsTitle;
	private String newsContent;
	private String newsResource;
	private String newsUrl;
	private Date newsPublishtime;
	private String newsSite;
	private String newsCatagory;
	private String webContent;
	

	public News() {
	}

	public News(int newsId, String newsTitle, String newsContent,
			String newsUrl, Date newsPublishtime) {
		this.newsId = newsId;
		this.newsTitle = newsTitle;
		this.newsContent = newsContent;
		this.newsUrl = newsUrl;
		this.newsPublishtime = newsPublishtime;
	}


	public int getNewsId() {
		return this.newsId;
	}

	public void setNewsId(int newsId) {
		this.newsId = newsId;
	}

	public String getNewsTitle() {
		return this.newsTitle;
	}

	public void setNewsTitle(String newsTitle) {
		this.newsTitle = newsTitle;
	}

	public String getNewsContent() {
		return this.newsContent;
	}

	public void setNewsContent(String newsContent) {
		this.newsContent = newsContent;
	}

	public String getNewsResource() {
		return this.newsResource;
	}

	public void setNewsResource(String newsResource) {
		this.newsResource = newsResource;
	}

	public String getNewsUrl() {
		return this.newsUrl;
	}

	public void setNewsUrl(String newsUrl) {
		this.newsUrl = newsUrl;
	}

	public Date getNewsPublishtime() {
		return this.newsPublishtime;
	}

	public void setNewsPublishtime(Date newsPublishtime) {
		this.newsPublishtime = newsPublishtime;
	}

	/**
	 * @return the newsSite
	 */
	public String getNewsSite() {
		return newsSite;
	}

	/**
	 * @param newsSite the newsSite to set
	 */
	public void setNewsSite(String newsSite) {
		this.newsSite = newsSite;
	}

	/**
	 * @return the newsCatagory
	 */
	public String getNewsCatagory() {
		return newsCatagory;
	}

	/**
	 * @param newsCatagory the newsCatagory to set
	 */
	public void setNewsCatagory(String newsCatagory) {
		this.newsCatagory = newsCatagory;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "News [newsId=" + newsId + ", newsTitle=" + newsTitle
				+ ", newsContent=" + newsContent + ", newsResource="
				+ newsResource + ", newsUrl=" + newsUrl + ", newsPublishtime="
				+ newsPublishtime + ", newsSite=" + newsSite
				+ ", newsCatagory=" + newsCatagory + "]";
	}

	public String getWebContent() {
		return webContent;
	}

	public void setWebContent(String webContent) {
		this.webContent = webContent;
	}



}
